services:
  service-a:
    build: .
    container_name: service-a
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    networks:
      - app-network

  service-b:
    build: .
    container_name: service-b
    ports:
      - "8001:8001"
    command: uvicorn second_main:app --host 0.0.0.0 --port 8001
    environment:
      - SERVICE_A_HOST=service-a
    depends_on:
      - service-a
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
